default:
  summary_length: 10
auth:
  algorithm: "HS256"
  access_token_expire_minutes: 0 # 0 = never
weaviate:
  url: "https://ai-document-search-backend-dev-95avppln.weaviate.network"
chatbot:
  verbose: false
  temperature: 0 # randomness, 0 = deterministic
